version: "3.9"
services:
  app:
    build: .
    container_name: remi-app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3001 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "3001:3001"
  app_frontend:
    container_name: remi-app-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/frontend/
      - node_modules:/frontend/node_modules/
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  node_modules: